# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# InspectMC
mod_version=1.0.0
maven_group=com.levelsfr.inspectmc
archives_name=inspectmc
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.1

# Loaders
fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1
neoforge_version=21.1.248
cloth_config_version=15.0.140
modmenu_version=11.0.3

# Optional Cobblemon diagnostics
os_cobblemon_library_version=1.1.0
cobblemon_version=1.8.1+1.21.1
cobblemon_min_version=1.8.1
cobblemon_max_version=1.9.0
kotlin_version=2.2.20
